% load packages
AXIS = lib.ecma.require(@lib.model.cRAR.axes.astro);

EXPORT.radius = @(R) lib.profile.anchor(...
	'x',		@(obj) AXIS.radius.fmap(obj),...
	'xq',		@(obj,X) R,...
	'xscale',	'log' ...
);

EXPORT.mass = @(M) lib.profile.anchor(...
	'x',		@(obj) AXIS.mass.fmap(obj),...
	'xq',		@(obj,X) M,...
	'xscale',	'log' ...
);

EXPORT.density = @(RHO) lib.profile.anchor(...
	'x',		@(obj) AXIS.density.fmap(obj),...
	'xq',		@(obj,X) RHO,...
	'xscale',	'log' ...
);

EXPORT.velocity = @(V) lib.profile.anchor(...
	'x',		@(obj) AXIS.velocity.fmap(obj),...
	'xq',		@(obj,X) V,...
	'xscale',	'log' ...
);