% load packages
AXIS	= lib.ecma.require(@lib.model.cRAR.axes.astro);

% set plot function for a profile p
EXPORT.radiusVsVelocity = @(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.radius,...
	'y',	AXIS.density,...
	'plot', {...
		'DisplayName',	lib.char.sprintf('$\theta_0 = %d$', p.data.theta0) ...
	}...
);