EXPORT.density = lib.profile.mapping(...
	'map',		@(obj) 1/obj.data.density(1),...
	'label',	'\rho_0'...
);

EXPORT.pressure = lib.profile.mapping(...
	'map',		@(obj) 1/obj.data.pressure(1),...
	'label',	'\rho_0 c^2'...
);

EXPORT.degeneracy = lib.profile.mapping(...
	'map',		@(obj) obj.data.theta0,...
	'label',	'\theta_0'...
);