ANCH = lib.ecma.require(@lib.model.cRAR.anchor);
MAP  = lib.ecma.require(@lib.model.cRAR.map);

fscale = @(obj,y) 1/ANCH.velocity_core.map('data', obj,'y', y);

EXPORT.radius = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,MAP.radius),...
	'label',	'r_c'...
);

EXPORT.density = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,obj.data.density),...
	'label',	'\rho_c'...
);

EXPORT.pressure = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,obj.data.pressure),...
	'label',	'P_c'...
);

EXPORT.mass = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,MAP.mass),...
	'label',	'M_c'...
);

EXPORT.velocity = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,MAP.velocity),...
	'label',	'v_c'...
);

EXPORT.potential = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,obj.data.potential),...
	'label',	'\nu_c'...
);

EXPORT.compactness = lib.profile.mapping(...
	'map',		@(obj) fscale(obj,MAP.compactness),...
	'label',	'\varphi_c'...
);