function varargout = Wp(varargin)
Q = lib.ecma.struct(...
	'nlinfit',	{},...
	'dW',		10,...
	varargin{:} ...
);

% load packages
ANCH	= lib.ecma.require(@lib.model.cRAR.anchor);
MAP		= lib.ecma.require(@lib.model.cRAR.map);

% set folution function
fWp		= @(obj) ANCH.velocity_plateau.map('data', obj, 'y', MAP.cutoff);
respWp	= lib.profile.response(...
	'map',			fWp,...
	'prediction',	Q.Wp ...
);

[varargout{1:nargout}] = lib.fitting.find('model', Q.model, 'query', respWp, 'fSolution', {
	@(vm,list) lib.model.cRAR.find.nlinfit.W0('model', vm, 'list', list)
	@(vm,list) lib.model.cRAR.find.gosect.W0('model',vm, 'list', list, 'dX', Q.dW)
});