% load packages
MAP			= lib.ecma.require(@lib.model.cRAR.map);
AXIS		= lib.ecma.require(@lib.model.cRAR.axes.astro);

% helpers
findGlobalMaximum	= @(x) find(findpeaks(x)==max(findpeaks(x)));
findGlobalMinumum	= @(x) find(-findpeaks(-x)==min(-findpeaks(-x)));

fcore		= @(X,Y) lib.num.get_extrema(X, Y, 1);
fplateau	= @(X,Y) lib.num.get_extrema(X,-Y, findGlobalMinumum(Y));
fhalo		= @(X,Y) lib.num.get_extrema(X, Y, findGlobalMinumum(Y)+1);

fR			= @(obj) obj.data.radius;

% center (r=0)
EXPORT.center = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) obj.data.radius(1),...
	'xscale',	'log' ...
);


% core based on rotation curve
EXPORT.velocity_core = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) exp(fcore(log(X),log(MAP.velocity.fmap(obj)))),...
	'xscale',	'log' ...
);

EXPORT.velocity_plateau = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) exp(fplateau(log(X),log(MAP.velocity.fmap(obj)))),...
	'xscale',	'log' ...
);

EXPORT.velocity_halo = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) exp(fhalo(log(X),log(MAP.velocity.fmap(obj)))),...
	'xscale',	'log' ...
);


% core based on mass profile
EXPORT.mass_core = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fcore(X,MAP.massDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.mass_plateau = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fplateau(X,MAP.massDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.mass_halo = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fhalo(X,MAP.massDiff.fmap(obj)),...
	'xscale',	'log' ...
);


% core based on degeneracy curve
EXPORT.degeneracy_core = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fcore(X,-MAP.degeneracyDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.degeneracy_plateau = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fplateau(X,-MAP.degeneracyDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.degeneracy_halo = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fhalo(X,-MAP.degeneracyDiff.fmap(obj)),...
	'xscale',	'log' ...
);


% core based on compactness curve
EXPORT.compactness_core = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fcore(X,MAP.compactness.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.compactness_plateau = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fplateau(X,MAP.compactness.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.compactness_halo = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fhalo(X,MAP.compactness.fmap(obj)),...
	'xscale',	'log' ...
);


% based on potential curve
EXPORT.potential_core = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fcore(X,MAP.potentialDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.potential_plateau = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fplateau(X,MAP.potentialDiff.fmap(obj)),...
	'xscale',	'log' ...
);

EXPORT.potential_halo = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) fhalo(X,MAP.potentialDiff.fmap(obj)),...
	'xscale',	'log' ...
);


% surface (r = r_s where density falls to 0)
EXPORT.surface = lib.profile.anchor(...
	'x',		fR,...
	'xq',		@(obj,X) obj.data.radius(end),...
	'xscale',	'log' ...
);
